# Projeto Integrador
## ETL com Python, SQLAlchemy e PostgreSQL

### Visão didática

Neste notebook vamos simular **todo o ETL em um único lugar**.

Depois, o mesmo processo será organizado em arquivos `.py`, aproximando o projeto de uma arquitetura de produção.

O cenário possui **dois bancos PostgreSQL**:

```text
LOJA_BRASIL                         DW
ERP / operacional                  Data Warehouse
      │                                  │
      │                                  ├── bronze
      │ ETL / Python                     ├── silver
      └─────────────────────────────────>├── gold
                                         │
                                         ↓
                                    SQL / BI
```

## Fontes

1. **Loja_Brasil:** ERP PostgreSQL
2. **IBGE:** API pública
3. **Excel:** metas comerciais

A separação é importante:

> O ERP registra as operações da empresa.  
> O DW recebe, trata e organiza os dados para análise.

In [ ]:
# Instalação, se necessário
# !pip install pandas sqlalchemy psycopg2-binary requests openpyxl

In [1]:
from sqlalchemy import create_engine, text
import pandas as pd
import requests

# Conexão com o ERP
engine_erp = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/loja_brasil"
)

# Conexão com o DW
engine_dw = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/dw"
)

print("Conexões configuradas.")

Conexões configuradas.

# 1. Preparando o Data Warehouse

O banco `dw` será separado do ERP.

Dentro dele criaremos os schemas:

```text
dw
├── bronze
├── silver
└── gold
```

In [2]:
from sqlalchemy import create_engine, text

admin_engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/postgres"
)

for db_name in ["dw"]:
    with admin_engine.connect().execution_options(isolation_level="AUTOCOMMIT") as conn:
        if not conn.execute(
            text("SELECT 1 FROM pg_database WHERE datname = 'dw'")
        ).scalar():
            conn.execute(text("CREATE DATABASE dw"))
            print("Banco 'dw' criado.")
        else:
            print("Banco 'dw' já existe.")

Banco 'dw' criado.

In [3]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    port=5432,
    user="postgres",
    password="postgres",
    dbname="postgres"
)

print("Conectou!")
conn.close()

Conectou!

In [4]:
with engine_dw.begin() as conn:
    conn.execute(text("CREATE SCHEMA IF NOT EXISTS bronze"))
    conn.execute(text("CREATE SCHEMA IF NOT EXISTS silver"))
    conn.execute(text("CREATE SCHEMA IF NOT EXISTS gold"))

print("Schemas do DW criados.")

Schemas do DW criados.

# 2. EXTRACT — ERP → Bronze

O Python se conecta ao banco `loja_brasil`, executa SQL e traz os dados para um DataFrame.

Depois, grava o resultado no banco `dw`, schema `bronze`.

```text
loja_brasil
     ↓
  SQLAlchemy
     ↓
   Pandas
     ↓
dw.bronze
```

In [ ]:
sql_vendas = """
SELECT
    p.id_pedido,
    p.data_pedido,
    p.status AS status_pedido,
    c.id_cliente,
    c.nome AS cliente,
    c.cidade,
    c.estado,
    i.id_produto,
    pr.nome AS produto,
    cat.nome AS categoria,
    m.nome AS marca,
    i.quantidade,
    i.preco_unitario,
    i.desconto
FROM vendas.pedidos p
INNER JOIN cadastro.clientes c
    ON c.id_cliente = p.id_cliente
INNER JOIN vendas.itens_pedido i
    ON i.id_pedido = p.id_pedido
INNER JOIN cadastro.produtos pr
    ON pr.id_produto = i.id_produto
INNER JOIN cadastro.categorias cat
    ON cat.id_categoria = pr.id_categoria
INNER JOIN cadastro.marcas m
    ON m.id_marca = pr.id_marca;
"""

df_vendas = pd.read_sql(sql_vendas, engine_erp)

df_vendas.to_sql(
    "erp_vendas",
    engine_dw,
    schema="bronze",
    if_exists="replace",
    index=False
)
print("Dados de vendas carregados para o DW (schema bronze).")

df_vendas.head()

,id_pedido,data_pedido,status_pedido,id_cliente,cliente,cidade,estado,id_produto,produto,categoria,marca,quantidade,preco_unitario,desconto
0,1,2025-02-10,Pendente,8,Henrique Martins,Jaraguá do Sul,SC,6,Calça Mom Feminina,Calças,Urban,2,159.9,0.0
1,1,2025-02-10,Pendente,8,Henrique Martins,Jaraguá do Sul,SC,13,Cinto de Couro,Acessórios,Serra Sul,3,79.9,5.0
2,1,2025-02-10,Pendente,8,Henrique Martins,Jaraguá do Sul,SC,2,Camiseta Polo Masculina,Camisetas,Estilo Brasil,4,89.9,10.0
3,2,2025-02-19,Entregue,15,Otávio Ribeiro,Chapecó,SC,11,Tênis Casual Branco,Calçados,Urban,3,199.9,5.0
4,2,2025-02-19,Entregue,15,Otávio Ribeiro,Chapecó,SC,18,Cachecol Tricot,Acessórios,Viva Moda,4,54.9,10.0

# 3. EXTRACT — API IBGE → Bronze

In [6]:
url_ibge = "https://servicodados.ibge.gov.br/api/v1/localidades/estados/42/municipios"

response = requests.get(url_ibge, timeout=30)
response.raise_for_status()

dados_ibge = response.json()

df_ibge = pd.DataFrame([
    {
        "id_ibge": municipio["id"],
        "cidade": municipio["nome"],
        "estado": municipio["microrregiao"]["mesorregiao"]["UF"]["sigla"],
        "regiao": municipio["microrregiao"]["mesorregiao"]["UF"]["regiao"]["nome"],
        "mesorregiao": municipio["microrregiao"]["mesorregiao"]["nome"],
        "microrregiao": municipio["microrregiao"]["nome"],
        "regiao_imediata": municipio["regiao-imediata"]["nome"],
        "regiao_intermediaria": municipio["regiao-imediata"]["regiao-intermediaria"]["nome"]
    }
    for municipio in dados_ibge
])

df_ibge.to_sql(
    "ibge_municipios",
    engine_dw,
    schema="bronze",
    if_exists="replace",
    index=False
)

df_ibge.head()

,id_ibge,cidade,estado,regiao,mesorregiao,microrregiao,regiao_imediata,regiao_intermediaria
0,4200051,Abdon Batista,SC,Sul,Serrana,Curitibanos,Joaçaba - Herval d'Oeste,Chapecó
1,4200101,Abelardo Luz,SC,Sul,Oeste Catarinense,Xanxerê,Xanxerê,Chapecó
2,4200200,Agrolândia,SC,Sul,Vale do Itajaí,Ituporanga,Rio do Sul,Blumenau
3,4200309,Agronômica,SC,Sul,Vale do Itajaí,Rio do Sul,Rio do Sul,Blumenau
4,4200408,Água Doce,SC,Sul,Oeste Catarinense,Joaçaba,Joaçaba - Herval d'Oeste,Chapecó

# 4. EXTRACT — Excel → Bronze

In [7]:
import openpyxl

df_metas = pd.read_excel("metas_vendas.xlsx")

df_metas.to_sql(
    "metas_vendas",
    engine_dw,
    schema="bronze",
    if_exists="replace",
    index=False
)

df_metas.head()

    ano  mes estado  meta_vendas
0  2025    1     SC         5000
1  2025    2     SC         5500
2  2025    3     SC         6000
3  2025    4     SC         6500
4  2025    5     SC         7000

# 5. SILVER — tratamento e integração

Agora o processamento deixa de consultar diretamente o ERP.

A Silver lê **somente a Bronze do DW**:

```text
bronze
   ↓
limpeza
padronização
cálculos
integrações
validações
   ↓
silver
```

In [8]:
df_vendas = pd.read_sql(
    "SELECT * FROM bronze.erp_vendas",
    engine_dw
)

df_ibge = pd.read_sql(
    "SELECT * FROM bronze.ibge_municipios",
    engine_dw
)

df_metas = pd.read_sql(
    "SELECT * FROM bronze.metas_vendas",
    engine_dw
)

In [9]:
df_vendas["data_pedido"] = pd.to_datetime(df_vendas["data_pedido"])
df_vendas["ano"] = df_vendas["data_pedido"].dt.year
df_vendas["mes"] = df_vendas["data_pedido"].dt.month

df_vendas["valor_item"] = (
    df_vendas["quantidade"]
    * df_vendas["preco_unitario"]
    * (1 - df_vendas["desconto"] / 100)
).round(2)

df_vendas = df_vendas[
    df_vendas["status_pedido"] != "Cancelado"
].copy()

df_vendas["cidade"] = df_vendas["cidade"].str.strip()
df_ibge["cidade"] = df_ibge["cidade"].str.strip()

df_vendas["estado"] = df_vendas["estado"].str.upper()
df_ibge["estado"] = df_ibge["estado"].str.upper()

df_vendas = df_vendas.merge(
    df_ibge,
    on=["cidade", "estado"],
    how="left"
)

df_vendas = df_vendas.merge(
    df_metas,
    on=["ano", "mes", "estado"],
    how="left"
)

print("Sem correspondência IBGE:",
      df_vendas["id_ibge"].isna().sum())
print("Sem correspondência de meta:",
      df_vendas["meta_vendas"].isna().sum())

df_vendas.head()

Sem correspondência IBGE: 0
Sem correspondência de meta: 0

,id_pedido,data_pedido,status_pedido,id_cliente,cliente,cidade,estado,id_produto,produto,categoria,...,ano,mes,valor_item,id_ibge,regiao,mesorregiao,microrregiao,regiao_imediata,regiao_intermediaria,meta_vendas
0,1,2025-02-10,Pendente,8,Henrique Martins,Jaraguá do Sul,SC,6,Calça Mom Feminina,Calças,...,2025,2,319.80,4208906,Sul,Norte Catarinense,Joinville,Joinville,Joinville,5500
1,1,2025-02-10,Pendente,8,Henrique Martins,Jaraguá do Sul,SC,13,Cinto de Couro,Acessórios,...,2025,2,227.72,4208906,Sul,Norte Catarinense,Joinville,Joinville,Joinville,5500
2,1,2025-02-10,Pendente,8,Henrique Martins,Jaraguá do Sul,SC,2,Camiseta Polo Masculina,Camisetas,...,2025,2,323.64,4208906,Sul,Norte Catarinense,Joinville,Joinville,Joinville,5500
3,2,2025-02-19,Entregue,15,Otávio Ribeiro,Chapecó,SC,11,Tênis Casual Branco,Calçados,...,2025,2,569.72,4204202,Sul,Oeste Catarinense,Chapecó,Chapecó,Chapecó,5500
4,2,2025-02-19,Entregue,15,Otávio Ribeiro,Chapecó,SC,18,Cachecol Tricot,Acessórios,...,2025,2,197.64,4204202,Sul,Oeste Catarinense,Chapecó,Chapecó,Chapecó,5500

In [10]:
df_vendas.to_sql(
    "vendas_tratadas",
    engine_dw,
    schema="silver",
    if_exists="replace",
    index=False
)

df_ibge.to_sql(
    "municipios",
    engine_dw,
    schema="silver",
    if_exists="replace",
    index=False
)

df_metas.to_sql(
    "metas_vendas",
    engine_dw,
    schema="silver",
    if_exists="replace",
    index=False
)

print("Silver carregada.")

Silver carregada.

# 6. GOLD — dados para análise

A Gold recebe os dados tratados da Silver e cria estruturas destinadas ao consumo analítico.

```text
silver
   ↓
regras de negócio
agregações
modelagem
   ↓
gold
```

In [11]:
df_vendas = pd.read_sql(
    "SELECT * FROM silver.vendas_tratadas",
    engine_dw
)

df_ibge = pd.read_sql(
    "SELECT * FROM silver.municipios",
    engine_dw
)

df_metas = pd.read_sql(
    "SELECT * FROM silver.metas_vendas",
    engine_dw
)

df_fato = df_vendas[
    [
        "id_pedido", "data_pedido", "id_cliente", "cliente",
        "cidade", "estado", "id_ibge", "id_produto",
        "produto", "categoria", "marca", "quantidade",
        "preco_unitario", "desconto", "valor_item"
    ]
].copy()

df_municipios = df_ibge[
    [
        "id_ibge", "cidade", "estado", "regiao",
        "mesorregiao", "microrregiao",
        "regiao_imediata", "regiao_intermediaria"
    ]
].copy()

df_resumo = (
    df_vendas
    .groupby(
        ["ano", "mes", "estado", "meta_vendas"],
        as_index=False
    )["valor_item"]
    .sum()
    .rename(columns={"valor_item": "vendas_realizadas"})
)

df_resumo["percentual_atingimento"] = (
    df_resumo["vendas_realizadas"]
    / df_resumo["meta_vendas"]
    * 100
).round(2)

df_resumo["situacao_meta"] = df_resumo[
    "percentual_atingimento"
].apply(
    lambda x: "Meta atingida" if x >= 100 else "Meta não atingida"
)

In [12]:
df_fato.to_sql(
    "fato_vendas", engine_dw,
    schema="gold", if_exists="replace", index=False
)

df_municipios.to_sql(
    "dim_municipios", engine_dw,
    schema="gold", if_exists="replace", index=False
)

df_metas.to_sql(
    "metas_vendas", engine_dw,
    schema="gold", if_exists="replace", index=False
)

df_resumo.to_sql(
    "fato_metas_mensais", engine_dw,
    schema="gold", if_exists="replace", index=False
)

print("Gold carregada.")

Gold carregada.

# 7. Arquitetura final

```text
                  LOJA_BRASIL
                  Banco ERP
                      │
                      │ SQLAlchemy + SQL
                      ↓
              ┌───────────────┐
              │   DW - BRONZE │
              │               │
              │ erp_vendas    │
              │ ibge_municipios
              │ metas_vendas  │
              └───────┬───────┘
                      ↓
              ┌───────────────┐
              │   DW - SILVER │
              │               │
              │ vendas_tratadas
              │ municipios    │
              │ metas_vendas  │
              └───────┬───────┘
                      ↓
              ┌───────────────┐
              │    DW - GOLD  │
              │               │
              │ fato_vendas   │
              │ dim_municipios│
              │ fato_metas... │
              └───────┬───────┘
                      ↓
                 SQL / BI
```

**ERP separado do DW. Código separado dos dados. Camadas separadas dentro do DW.**

# 8. Como isso vira produção?

O notebook é ótimo para aprender e demonstrar o processo.

Em produção, separamos as responsabilidades:

```text
src/
├── config.py
├── setup_dw.py
├── extract_erp.py
├── extract_ibge.py
├── extract_excel.py
├── silver.py
├── gold.py
└── run_etl.py
```

O fluxo passa a ser:

```text
extract_erp.py  ─┐
extract_ibge.py  ├──→ Bronze
extract_excel.py ┘
                    ↓
                 silver.py
                    ↓
                  Silver
                    ↓
                  gold.py
                    ↓
                   Gold
```

Um orquestrador, como Airflow, poderia posteriormente controlar a ordem e as dependências.

# 9. Principal aprendizado

O objetivo não é apenas aprender `pd.read_sql()` ou `to_sql()`.

O aluno deve compreender a arquitetura:

```text
FONTE
  ↓
EXTRACT
  ↓
BRONZE
  ↓
TRANSFORM
  ↓
SILVER
  ↓
TRANSFORM / MODELAGEM
  ↓
GOLD
  ↓
ANÁLISE
```

> **Loja_Brasil é o sistema operacional.  
> DW é o ambiente analítico.  
> Bronze preserva a extração.  
> Silver trata e integra.  
> Gold prepara para o negócio.**